### PR TITLE
Making the package work with FindPNG.cmake too (corrected and re-created pull request)

### PR DESCRIPTION
**Pull request by ghost**
Hi @solvingj

I know I have access to directly modify this package but, since I wasn't the one who initially created it, I thought to introduce a pull request so that I don't "vandalize" it so to speak. I've tried to compile https://github.com/sigmoidal/conan-freetype locally and it wouldn't build because it was referencing this package and cmake couldn't find the packaged FindPNG.cmake module which is needed in this case. It seems that, according to @lasote's contribution, we still need a package method in the conanfile, in order to properly include the FindPNG module in the package.

### CODE REVIEW

**Comment by zamazan4ik** [comment]
@solvingj @uilianries can we merge it into stable branch directly? or we should merge into testing branch, and only after some testing merge into stable branch?

@dimi309 @lasote thank you for the fix :-)

**Review by uilianries — APPROVED** [review]
LGTM

**Comment by uilianries** [comment]
@dimi309 You can use `testing` branch for that instead of create a fork. Anyway, many thanks for the fix!

**Comment by ghost** [comment]
You're welcome! I'll do it like you said next time. I've noticed there's a problem with the MinGW build too. I'm looking into it.

**Comment by solvingj** [comment]
I prefer PR’s to testing branch to avoid collisions of multiple devs at one time.

**Comment by ghost** [comment]
Ok, sounds good!

**Pull request merged**
